todolist/urls.py
from django.urls import path
from todolist import views


app_name = 'todolist'

urlpatterns = [
    path('', views.index, name='home'),
    path('get-tasks/<str:collection_slug>', views.get_tasks, name='get-tasks'),
    path('add-task/', views.add_task, name='add-task'),
    path('remove-task/<int:task_pk>', views.remove_task, name='remove-task'),
    path('toggle-done/<int:task_pk>', views.toggle_done, name='toggle-done'),
    path('add-collection', views.add_collection, name='add-collection'),
    path('remove-collection/<int:collection_pk>', views.remove_collection, name='remove-collection'),
]

todolist/models.py
from django.db import models


# COLLECTION MODEL
class Collection(models.Model):
    name = models.CharField(max_length=200)
    slug = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    @classmethod
    def get_default_collection(cls) -> "Collection":
        collection, _ = Collection.objects.get_or_create(name='Default', slug='_default')
        return collection


# TASK MODEL
class Task(models.Model):
    title = models.CharField(max_length=200)
    done = models.BooleanField(default=False)
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

todolist/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, reverse
from django.utils.text import slugify
from django.utils.html import escape

from todolist.models import Collection, Task


def index(request):
    context = {}
    collection_slug = request.GET.get('collection')
    collections = Collection.objects.order_by('slug')

    if not collection_slug:
        collection = Collection.get_default_collection()
        return redirect(f"{reverse('todolist:home')}?collection=_default")
    
    collection = get_object_or_404(Collection, slug=collection_slug)
    tasks = collection.task_set.all()

    return render(request, "todolist/index.html", context={
        "collection": collection,
        "collections": collections,
        "tasks": tasks,
        "current_user": request.user.username
    })


def get_tasks(request, collection_slug):
    collection = get_object_or_404(Collection, slug=collection_slug)
    tasks = collection.task_set.all()
    return render(request, "todolist/tasks.html", context={
        "tasks": tasks
    })
    

def add_task(request):
    collection = Collection.objects.get(slug=request.POST.get('collection'))
    task_name = escape(request.POST.get("task"))
    if task_name == "":
        return
    task = Task.objects.create(title=task_name, collection=collection)
    return render(request, 'todolist/task.html', context={
        "task": task
    })


def remove_task(request, task_pk):
    task = get_object_or_404(Task, id=task_pk)
    task.delete()
    collection = escape(request.POST.get("collection"))
    return get_tasks(request, collection)


def toggle_done(request, task_pk):
    task = get_object_or_404(Task, id=task_pk)
    task.done = not task.done
    task.save()
    collection = task.collection.slug
    return get_tasks(request, collection)


def add_collection(request):
    collection_name = escape(request.POST.get("collection"))
    if collection_name == "":
        return
    collection, created = Collection.objects.get_or_create(name=collection_name,
                                                        slug=slugify(collection_name))
    if not created:
        return HttpResponse("This collection already exists")
    return render(request, "todolist/collection.html", context={"collection": collection})


def remove_collection(request, collection_pk):
    collection = get_object_or_404(Collection, id=collection_pk)
    collection.delete()
    return redirect('todolist:home')

todolist/templates/todolist/collection.html
{% load static %}
<form   method="POST" class="todolist-collection">
    {% csrf_token %}
    <button hx-post="{% url 'todolist:get-tasks' collection.slug %}"
            hx-target="#tasks"
            hx-push-url="?collection={{ collection.slug }}"
            hx-swap="innerHTML"
            type="submit"
            class="todolist-nav-button w-75">
        {{ collection.name }}
    </button>
    <a href="{% url 'todolist:remove-collection' collection.pk %}" class="todolist-action-button">
            <img src="{% static 'todolist/img/todolist-icon-remove.png' %}" class="todolist-icon">
    </a>
</form>

todolist/templates/todolist/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- TITLE BAR -->
    <header class="todolist-title">
        <div class="todolist-log">
            <p>{{ current_user }}</p>
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Logout</button>
            </form>
        </div>
        <h1>ToDoLists</h1>
    </header>

    <main>
        <!-- COLLECTIONS -->
        <div class="col-20 todolist-nav">
            <!-- COLLECTIONS LIST -->
            <nav id="collections">
                {% for collection in collections %}
                    {% include 'todolist/collection.html' with collection=collection %}
                {% endfor %}
            </nav>
            <!-- ADD A COLLECTION -->
            <form class="form-add-collection" method="POST">
                {% csrf_token %}
                <input class="todolist-input-add w-75" type='text' placeholder='new list...' name="collection"/>
                <button class="todolist-button-add w-75"
                        hx-post="{% url 'todolist:add-collection' %}"
                        hx-target="#collections"
                        hx-swap="beforeend">
                        Add
                </button>
            </form>
        </div>


        <!-- TASKS -->
        <div class="col-80 main-content">
            <div class="content-title">
                <h2 class="todolist-current-collection">{{ collection }}</h2>
                <div>
                    <form class="form-add-task" method="POST">
                        {% csrf_token %}
                        <input class="todolist-input-add" type='text' placeholder='new task...' name="task"/>
                        <button class="todolist-button-add"
                                hx-post="{% url 'todolist:add-task' %}"
                                hx-target="#tasks"
                                hx-vals="js:{ collection: getCollectionFromUrl() }"
                                hx-swap="beforeend"
                                type=submit>Add</button>
                    </form>
                </div>
            </div>
            <div id="tasks">
                {% include 'todolist/tasks.html' with tasks=tasks %}
            </div>
        </div>
    </main>
{% endblock %}

todolist/templates/todolist/task.html
<form   method="POST" 
        class="todolist-task {% if task.done %}task-done{% endif %}">
    {% csrf_token %}
    <p>{{ task.title }}</p>
    <button hx-post="{% url 'todolist:toggle-done' task.pk %}"
            hx-target="#tasks"
            hx-swap="innerHTML"
            type="submit" 
            name="task-done"
            class="task-button button-done">
        Done
    </button>
    <button hx-post="{% url 'todolist:remove-task' task.pk %}"
            hx-target="#tasks"
            hx-vals="js:{ collection: getCollectionFromUrl() }"
            hw-swap="outerHTML"
            type="submit"
            class="task-button button-remove">
        Remove
    </button>
</form>

todolist/templates/todolist/tasks.html
{% for task in tasks %}
    {% include 'todolist/task.html' with task=task %}
{% endfor %}